insert into items (itemname, price, closed) values ('Tea - Jasmin Green', 0.92, false);
insert into items (itemname, price, closed) values ('Grapes - Red', 0.76, false);
insert into items (itemname, price, closed) values ('Coffee - Ristretto Coffee Capsule', 1.36, false);
insert into items (itemname, price, closed) values ('Nantucket - 518ml', 1.07, false);
insert into items (itemname, price, closed) values ('Ice Cream - Strawberry', 3.07, false);
insert into items (itemname, price, closed) values ('Spinach - Frozen', 0.76, false);
insert into items (itemname, price, closed) values ('Pea - Snow', 1.1, false);
insert into items (itemname, price, closed) values ('Cranberries - Dry', 1.41, false);
insert into items (itemname, price, closed) values ('Dried Cranberries', 2.83, false);
insert into items (itemname, price, closed) values ('Grapefruit - Pink', 2.67, false);
