insert into items (item_id, itemname, price, closed) values (1, 'Flavouring Vanilla Artificial', 2.42, false);
insert into items (item_id, itemname, price, closed) values (2, 'Soup - Campbells Mac N Cheese', 0.72, false);
insert into items (item_id, itemname, price, closed) values (3, 'Versatainer Nc - 888', 2.2, false);
insert into items (item_id, itemname, price, closed) values (4, 'Beer - Camerons Auburn', 0.72, false);
insert into items (item_id, itemname, price, closed) values (5, 'Wine - Saint Emilion Calvet', 2.88, false);
insert into items (item_id, itemname, price, closed) values (6, 'Nori Sea Weed', 3.07, false);
insert into items (item_id, itemname, price, closed) values (7, 'Paper - Brown Paper Mini Cups', 1.73, false);
insert into items (item_id, itemname, price, closed) values (8, 'Nantucket Orange Juice', 1.0, false);
insert into items (item_id, itemname, price, closed) values (9, 'Juice - Orangina', 2.25, false);
insert into items (item_id, itemname, price, closed) values (10, 'Oil - Peanut', 3.3, false);
insert into items (item_id, itemname, price, closed) values (11, 'Wine - Zinfandel Rosenblum', 3.2, false);
insert into items (item_id, itemname, price, closed) values (12, 'Wine - Red, Mosaic Zweigelt', 1.4, false);
insert into items (item_id, itemname, price, closed) values (13, 'Jam - Strawberry, 20 Ml Jar', 3.37, false);
insert into items (item_id, itemname, price, closed) values (14, 'Seedlings - Clamshell', 0.77, false);
insert into items (item_id, itemname, price, closed) values (15, 'Nut - Pecan, Pieces', 1.15, false);
insert into items (item_id, itemname, price, closed) values (16, 'Salmon - Sockeye Raw', 0.69, false);
insert into items (item_id, itemname, price, closed) values (17, 'Orange Roughy 4/6 Oz', 2.84, false);
insert into items (item_id, itemname, price, closed) values (18, 'Cleaner - Pine Sol', 1.38, false);
insert into items (item_id, itemname, price, closed) values (19, 'Mushrooms - Honey', 0.83, false);
insert into items (item_id, itemname, price, closed) values (20, 'Yogurt - Raspberry, 175 Gr', 3.37, false);
insert into items (item_id, itemname, price, closed) values (21, 'Veal - Nuckle', 1.01, false);
insert into items (item_id, itemname, price, closed) values (22, 'Wine - Charddonnay Errazuriz', 2.08, false);
insert into items (item_id, itemname, price, closed) values (23, 'Glass Clear 7 Oz Xl', 2.27, false);
insert into items (item_id, itemname, price, closed) values (24, 'Ocean Spray - Ruby Red', 2.66, false);
insert into items (item_id, itemname, price, closed) values (25, 'Cheese - Brick With Pepper', 0.68, false);
insert into items (item_id, itemname, price, closed) values (26, 'Lobster - Cooked', 3.03, false);
insert into items (item_id, itemname, price, closed) values (27, 'Rice Pilaf, Dry,package', 1.52, false);
insert into items (item_id, itemname, price, closed) values (28, 'Venison - Striploin', 1.02, false);
insert into items (item_id, itemname, price, closed) values (29, 'Rosemary - Dry', 2.08, false);
insert into items (item_id, itemname, price, closed) values (30, 'Shrimp - Black Tiger 13/15', 0.69, false);
