insert into companies (company_id, compname, address, email, country, route) values (1, 'Quigley-Bruen', '80082 Park Meadow Court', 'cniles0@aboutads.info', 'ID', 32);
insert into companies (company_id, compname, address, email, country, route) values (2, 'Lesch, Macejkovic and Towne', '0 Swallow Street', 'fcrickmer1@booking.com', 'YE', 25);
insert into companies (company_id, compname, address, email, country, route) values (3, 'Jaskolski-Gutkowski', '2 Loeprich Way', 'gkenneford2@msu.edu', 'SE', 28);
insert into companies (company_id, compname, address, email, country, route) values (4, 'Rippin-Quigley', '01 Dahle Road', 'aroberti3@free.fr', 'AM', 49);
insert into companies (company_id, compname, address, email, country, route) values (5, 'Schultz LLC', '51416 Kennedy Parkway', 'dmckellar4@rediff.com', 'PK', 47);
insert into companies (company_id, compname, address, email, country, route) values (6, 'Wilkinson, Stehr and Schuppe', '191 Menomonie Pass', 'gchilders5@upenn.edu', 'ID', 16);
insert into companies (company_id, compname, address, email, country, route) values (7, 'Thiel Group', '84 Hauk Way', 'lmartell6@ft.com', 'RU', 1);
insert into companies (company_id, compname, address, email, country, route) values (8, 'Nader LLC', '3 Springs Alley', 'ccasotti7@domainmarket.com', 'UA', 49);
insert into companies (company_id, compname, address, email, country, route) values (9, 'Parker Group', '3 Forest Avenue', 'mgorton8@google.co.uk', 'PL', 50);
insert into companies (company_id, compname, address, email, country, route) values (10, 'Anderson-Raynor', '18 Vidon Court', 'bfiloniere9@feedburner.com', 'US', 26);
insert into companies (company_id, compname, address, email, country, route) values (11, 'Macejkovic, Stehr and Harber', '444 Forest Street', 'cmardeea@cnn.com', 'NG', 47);
insert into companies (company_id, compname, address, email, country, route) values (12, 'Bednar and Sons', '81 Bluejay Trail', 'arentonb@jimdo.com', 'UA', 11);
insert into companies (company_id, compname, address, email, country, route) values (13, 'Daugherty, Schroeder and Waters', '614 Homewood Hill', 'cmursellc@unblog.fr', 'CN', 45);
insert into companies (company_id, compname, address, email, country, route) values (14, 'Heathcote-Collins', '0229 Judy Circle', 'wslinnd@redcross.org', 'PH', 28);
insert into companies (company_id, compname, address, email, country, route) values (15, 'Lowe LLC', '445 Onsgard Avenue', 'cturbane@artisteer.com', 'LT', 24);
insert into companies (company_id, compname, address, email, country, route) values (16, 'Breitenberg-Mraz', '2735 Bartelt Park', 'sjorissenf@state.tx.us', 'SE', 13);
insert into companies (company_id, compname, address, email, country, route) values (17, 'Kris and Sons', '96 Toban Park', 'aerdesg@tamu.edu', 'CN', 47);
insert into companies (company_id, compname, address, email, country, route) values (18, 'Wilkinson and Sons', '738 Twin Pines Place', 'nmattekh@ehow.com', 'NI', 10);
insert into companies (company_id, compname, address, email, country, route) values (19, 'Cummings-Hettinger', '410 Huxley Junction', 'nbreezei@usa.gov', 'PT', 12);
insert into companies (company_id, compname, address, email, country, route) values (20, 'Cassin LLC', '78827 Clove Place', 'fsearj@oracle.com', 'BR', 36);
insert into companies (company_id, compname, address, email, country, route) values (21, 'Lueilwitz, Toy and Waters', '0919 Carberry Place', 'rdianok@earthlink.net', 'ID', 47);
insert into companies (company_id, compname, address, email, country, route) values (22, 'Walsh, Hoppe and Prohaska', '2389 Meadow Valley Court', 'fcorbridgel@surveymonkey.com', 'ID', 22);
insert into companies (company_id, compname, address, email, country, route) values (23, 'Hauck-Reichert', '85 Graceland Court', 'awattsm@auda.org.au', 'NP', 40);
insert into companies (company_id, compname, address, email, country, route) values (24, 'Dibbert-Roob', '673 Artisan Street', 'jpetrun@adobe.com', 'PK', 41);
insert into companies (company_id, compname, address, email, country, route) values (25, 'Sauer and Sons', '50736 Forest Dale Center', 'ohatjeo@va.gov', 'CN', 49);
insert into companies (company_id, compname, address, email, country, route) values (26, 'Collier LLC', '4085 Darwin Parkway', 'rantrackp@nba.com', 'PA', 11);
insert into companies (company_id, compname, address, email, country, route) values (27, 'Volkman LLC', '27 Memorial Junction', 'rpoutonq@nhs.uk', 'PH', 31);
insert into companies (company_id, compname, address, email, country, route) values (28, 'Bradtke-Rosenbaum', '8 Arrowood Circle', 'ibothbier@t-online.de', 'BR', 11);
insert into companies (company_id, compname, address, email, country, route) values (29, 'Breitenberg LLC', '5 Meadow Ridge Plaza', 'mpraundls@goo.ne.jp', 'PH', 6);
insert into companies (company_id, compname, address, email, country, route) values (30, 'Treutel Group', '00668 Pepper Wood Pass', 'kbandierat@bbc.co.uk', 'PT', 10);
insert into companies (company_id, compname, address, email, country, route) values (31, 'Eichmann, Mayert and Rempel', '4244 Green Center', 'mbreukelmanu@wordpress.org', 'PL', 39);
insert into companies (company_id, compname, address, email, country, route) values (32, 'Tremblay, Kohler and Luettgen', '45 Blue Bill Park Lane', 'gtomasekv@themeforest.net', 'MN', 35);
insert into companies (company_id, compname, address, email, country, route) values (33, 'Ward Inc', '9 Scofield Alley', 'bemanuelovw@dion.ne.jp', 'US', 28);
insert into companies (company_id, compname, address, email, country, route) values (34, 'Collins LLC', '8136 Dapin Point', 'dferyx@technorati.com', 'CN', 8);
insert into companies (company_id, compname, address, email, country, route) values (35, 'Parker Inc', '30 Glendale Road', 'pserotskyy@disqus.com', 'PS', 45);
insert into companies (company_id, compname, address, email, country, route) values (36, 'Kiehn Group', '7879 Luster Trail', 'kdudingz@noaa.gov', 'CN', 2);
insert into companies (company_id, compname, address, email, country, route) values (37, 'Cassin-Klocko', '55 Ridge Oak Junction', 'cbecke10@twitpic.com', 'CN', 43);
insert into companies (company_id, compname, address, email, country, route) values (38, 'Stiedemann-Kovacek', '662 Dakota Lane', 'jmelville11@scribd.com', 'RU', 18);
insert into companies (company_id, compname, address, email, country, route) values (39, 'Wisozk-Graham', '85 Springs Pass', 'eduffill12@cmu.edu', 'SE', 9);
insert into companies (company_id, compname, address, email, country, route) values (40, 'Walker-Welch', '8669 Judy Road', 'mgantzer13@nbcnews.com', 'US', 10);
insert into companies (company_id, compname, address, email, country, route) values (41, 'Sipes-Greenholt', '1588 Hoffman Alley', 'beversley14@mozilla.org', 'US', 45);
insert into companies (company_id, compname, address, email, country, route) values (42, 'Welch-Beier', '918 Raven Road', 'asimenel15@smugmug.com', 'JP', 32);
insert into companies (company_id, compname, address, email, country, route) values (43, 'Wolf-Kuhlman', '3367 Florence Hill', 'djacketts16@naver.com', 'BY', 16);
insert into companies (company_id, compname, address, email, country, route) values (44, 'Kozey-Goodwin', '3470 Evergreen Center', 'abrookson17@mysql.com', 'CN', 6);
insert into companies (company_id, compname, address, email, country, route) values (45, 'Funk, Bernier and Schmeler', '4 8th Alley', 'trobet18@timesonline.co.uk', 'PH', 45);
insert into companies (company_id, compname, address, email, country, route) values (46, 'Nikolaus-Satterfield', '42 Fallview Hill', 'ivandervelde19@indiatimes.com', 'NL', 29);
insert into companies (company_id, compname, address, email, country, route) values (47, 'Barton-Zulauf', '0 Arkansas Park', 'iwoodruffe1a@walmart.com', 'RU', 45);
insert into companies (company_id, compname, address, email, country, route) values (48, 'Waters and Sons', '5839 Melby Circle', 'gchatelot1b@sun.com', 'SY', 23);
insert into companies (company_id, compname, address, email, country, route) values (49, 'Prosacco, Bruen and Hammes', '43 Center Terrace', 'vhandrahan1c@i2i.jp', 'JP', 39);
insert into companies (company_id, compname, address, email, country, route) values (50, 'Swaniawski Inc', '43 Harper Trail', 'tvatcher1d@a8.net', 'PE', 23);
