insert into companies (compname, address, email, country, route) values ('Labadie Group', '8717 Brentwood Park', 'mdonati0@archive.org', 'DO', 3);
insert into companies (compname, address, email, country, route) values ('Barrows, O''Reilly and Klocko', '533 Ronald Regan Court', 'etowsey1@i2i.jp', 'CN', 14);
insert into companies (compname, address, email, country, route) values ('Cassin and Sons', '6 Maryland Point', 'flythgoe2@angelfire.com', 'ID', 9);
insert into companies (compname, address, email, country, route) values ('Crooks-Douglas', '05 Little Fleur Road', 'gfenge3@answers.com', 'TH', 17);
insert into companies (compname, address, email, country, route) values ('Conroy-Tremblay', '5 Montana Hill', 'gcarle4@symantec.com', 'TJ', 18);
insert into companies (compname, address, email, country, route) values ('Kovacek-Gutkowski', '85611 Laurel Court', 'nbockh5@ask.com', 'BR', 17);
insert into companies (compname, address, email, country, route) values ('Bailey-Emmerich', '263 Eggendart Court', 'rparlet6@skype.com', 'NA', 4);
insert into companies (compname, address, email, country, route) values ('Jerde, Yundt and Nikolaus', '42661 Badeau Avenue', 'cbuy7@google.co.uk', 'ID', 9);
insert into companies (compname, address, email, country, route) values ('Kovacek and Sons', '64540 Heffernan Terrace', 'vpetrillo8@ameblo.jp', 'CN', 16);
insert into companies (compname, address, email, country, route) values ('Ankunding, Johnston and Lebsack', '0988 Tomscot Avenue', 'epaolillo9@liveinternet.ru', 'JM', 2);
insert into companies (compname, address, email, country, route) values ('Frami-Klein', '68557 Havey Drive', 'tabbysa@sohu.com', 'ID', 11);
insert into companies (compname, address, email, country, route) values ('Heller-Weber', '79649 Kipling Crossing', 'vchatinb@soundcloud.com', 'CN', 9);
insert into companies (compname, address, email, country, route) values ('Williamson-Rolfson', '14126 Monument Place', 'jlafeec@tumblr.com', 'US', 6);
insert into companies (compname, address, email, country, route) values ('Jacobs-Flatley', '15 Mockingbird Center', 'kgoldsbroughd@army.mil', 'TZ', 16);
insert into companies (compname, address, email, country, route) values ('Gottlieb LLC', '59631 Colorado Avenue', 'rivanuschkae@linkedin.com', 'CN', 11);
insert into companies (compname, address, email, country, route) values ('Windler-Rogahn', '2881 Carioca Street', 'aarnoldf@usnews.com', 'PL', 7);
insert into companies (compname, address, email, country, route) values ('Bashirian, Rice and Bailey', '520 Hanson Avenue', 'acastong@npr.org', 'US', 5);
insert into companies (compname, address, email, country, route) values ('Corkery-Harris', '61 Kedzie Center', 'arobineth@google.fr', 'KH', 12);
insert into companies (compname, address, email, country, route) values ('Skiles-Weimann', '2263 Del Mar Hill', 'fwaterlandi@stanford.edu', 'CA', 19);
insert into companies (compname, address, email, country, route) values ('Mante-Lowe', '3549 Evergreen Parkway', 'dglazej@networkadvertising.org', 'ID', 1);
