insert into items (itemname, price, closed) values ('Flavouring Vanilla Artificial', 2.42, false);
insert into items (itemname, price, closed) values ('Soup - Campbells Mac N Cheese', 0.72, false);
insert into items (itemname, price, closed) values ('Versatainer Nc - 888', 2.2, false);
insert into items (itemname, price, closed) values ('Beer - Camerons Auburn', 0.72, false);
insert into items (itemname, price, closed) values ('Wine - Saint Emilion Calvet', 2.88, false);
insert into items (itemname, price, closed) values ('Nori Sea Weed', 3.07, false);
insert into items (itemname, price, closed) values ('Paper - Brown Paper Mini Cups', 1.73, false);
insert into items (itemname, price, closed) values ('Nantucket Orange Juice', 1.0, false);
insert into items (itemname, price, closed) values ('Juice - Orangina', 2.25, false);
insert into items (itemname, price, closed) values ('Oil - Peanut', 3.3, false);
insert into items (itemname, price, closed) values ('Wine - Zinfandel Rosenblum', 3.2, false);
insert into items (itemname, price, closed) values ('Wine - Red, Mosaic Zweigelt', 1.4, false);
insert into items (itemname, price, closed) values ('Jam - Strawberry, 20 Ml Jar', 3.37, false);
insert into items (itemname, price, closed) values ('Seedlings - Clamshell', 0.77, false);
insert into items (itemname, price, closed) values ('Nut - Pecan, Pieces', 1.15, false);
insert into items (itemname, price, closed) values ('Salmon - Sockeye Raw', 0.69, false);
insert into items (itemname, price, closed) values ('Orange Roughy 4/6 Oz', 2.84, false);
insert into items (itemname, price, closed) values ('Cleaner - Pine Sol', 1.38, false);
insert into items (itemname, price, closed) values ('Mushrooms - Honey', 0.83, false);
insert into items (itemname, price, closed) values ('Yogurt - Raspberry, 175 Gr', 3.37, false);
insert into items (itemname, price, closed) values ('Veal - Nuckle', 1.01, false);
insert into items (itemname, price, closed) values ('Wine - Charddonnay Errazuriz', 2.08, false);
insert into items (itemname, price, closed) values ('Glass Clear 7 Oz Xl', 2.27, false);
insert into items (itemname, price, closed) values ('Ocean Spray - Ruby Red', 2.66, false);
insert into items (itemname, price, closed) values ('Cheese - Brick With Pepper', 0.68, false);
insert into items (itemname, price, closed) values ('Lobster - Cooked', 3.03, false);
insert into items (itemname, price, closed) values ('Rice Pilaf, Dry,package', 1.52, false);
insert into items (itemname, price, closed) values ('Venison - Striploin', 1.02, false);
insert into items (itemname, price, closed) values ('Rosemary - Dry', 2.08, false);
insert into items (itemname, price, closed) values ('Shrimp - Black Tiger 13/15', 0.69, false);
